# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends usage stats. Change to false to opt out.
install! 'cocoapods', :share_schemes_for_development_targets => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Set deployment target to 13.0 for all pods to avoid version mismatch errors
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
